chore: switched to coverall

diff --git a/.github/workflows/test-coverage.yaml b/.github/workflows/test-coverage.yaml
--- a/.github/workflows/test-coverage.yaml
+++ b/.github/workflows/test-coverage.yaml
@@ -26,8 +26,14 @@ jobs:
       run: ./vendor/bin/phpstan analyse --memory-limit=2G
       
     - name: Run Tests with Coverage
-      run: XDEBUG_MODE=coverage ./vendor/bin/pest --coverage --exclude-group wip --coverage-clover=clover.xml
-          
+      run: |
+        ./vendor/bin/pest --coverage-clover=clover.xml
+    
+    - name: Display Coverage File
+      run: |
+        ls -la clover.xml || echo "clover.xml not found"
+        pwd
+        
     - name: Upload coverage results to Coveralls
       env:
         COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
